### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by jonahbron** [kellerkindt/w5500#16]
Add support for TCP sockets.

**Comment by andresv** [comment]
There is a fork with TCP support: https://github.com/ninjasource/w5500/blob/master/src/lib.rs#L449

And here is a demo that uses that fork with websockets: https://github.com/ninjasource/led-display-websocket-demo/blob/master/led-display-hardware/src/main.rs

**Comment by kellerkindt** [comment]
Suppoert for TCP-Clients just got merged thanks to @ryan-summers  #24

**Comment by elpiel** [comment]
Awesome! Should this issue be closed then?
