### ISSUE TITLE
Vertical Integration

### ISSUE THREAD

**Issue by jonahbron** [kellerkindt/w5500#17]
Are there any higher-level network libraries/traits we could integrate with to allow use of the capabilities of the chip more directly?  Right now any dev who uses the driver must write their own code to accomplish their exact task.  But for more complex tasks (say a web server), it seems like the driver should be able to talk to some other library with that capability.  Thoughts?

**Comment by jonahbron** [comment]
The `std` crate has a `net` module with a UdpSocket struct.  There appears to be no way to replace the implementation.  But we might consider at least emulating the interface, to improve usability for devs who have already worked with UDP _outside_ of embedded platforms.

**Comment by MathiasKoch** [comment]
Relevant issue: https://github.com/rust-embedded/embedded-hal/issues/146

**Comment by ryan-summers** [comment]
`embedded-nal` is now being taken over by the rust-embedded-community. I'm using it as a driver for `minimq`, (no_std MQTT client) and have implemented TCP support + embedded-nal abstractions to a fork of this repo that I'd be happy to PR in.

The embedded-nal provides an abstract API that various network stacks can implement to allow higher level protocols to be implemented without caring who provides the underlying socket implementations. This allows you to do something like MQTT or other socket-based protocols that targets a variety of network stacks (such as on-board smoltcp or off-board W5500 stacks, as in my use case).

**Comment by kellerkindt** [comment]
Hey @ryan-summers, PRs are welcome! :)

**Comment by jonahbron** [comment]
Resolved by #26
