### ISSUE TITLE
How to reference your library with const_fn feature

### ISSUE THREAD

**Issue by ninjasource** [kellerkindt/w5500#2]
Hi,

When I reference your library in my own project and build it I get the following compiler error message:
   Compiling w5500 v0.1.5
error[E0554]: #![feature] may not be used on the stable release channel
 --> C:\Users\xxxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\w5500-0.1.5\src\lib.rs:3:1
  |
3 | #![feature(const_fn)]
  | ^^^^^^^^^^^^^^^^^^^^^

w5500 = "0.1.5"
latest rust stable build
What would I need to set up in my Cargo.toml file or what parameters do I need to pass to cargo build to use your library. Thanks!

**Comment by ninjasource** [comment]
I figured it out. The crate you published on crates.io does not seem to work but referencing your repo directly does. For anyone else having this problem, this entry in Cargo.toml works for me:

[dependencies]
w5500 = { git = "https://github.com/kellerkindt/w5500.git" }

**Comment by kellerkindt** [comment]
Thanks for the poke. I updated the version on crates.io which should now also work :)
