### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by FrozenDroid** [kellerkindt/w5500#3]
Hi, I may be interested in collaborating and using this project, but I need to know how this project is licensed. Thanks!

**Comment by kellerkindt** [comment]
Hope that helps :)

**Comment by kellerkindt** [comment]
I am currently testing whether refactoring the crate to something like the following code snippet is an actual improvement.
```rust
    let mut w5500: W5500 = W5500::new(&mut cs_w5500);
    let mut udp_server_socket: Option<UdpServerSocket> = {
        || {
            let mut w5500: ActiveW5500<_> = w5500.activate(&mut spi).ok()?;
            let socket: UninitializedSocket = w5500.take_socket(Socket::Socket0)?;
            (&mut w5500, socket).try_into_udp_server_socket(1234).ok()
        }
    }();

    let mut buffer = [0u8; 256];
    if let (Some(ref mut w5500), Some(ref udp)) = (w5500.activate(&mut spi).ok(), udp_server_socket) {
        let result = (w5500, udp).try_receive(&mut buffer[..]);
    }
```

The state of an socket is then enforced by the compiler, because of special implementations for 

```rust
(&mut ActiveW5500, &UdpSocket).send(...)
(&mut ActiveW5500, &UdpServerSocket).receive(...)
```
and at some point upcoming

```rust
(&mut ActiveW5500, &TcpSocket).send(...)
(&mut ActiveW5500, &TcpServerSocket).accept()
```

**Comment by FrozenDroid** [comment]
That's a good idea, helps with safety of the sockets.
I need implementations for TCP, DHCP, DNS, HTTP, etc.
I'd work on those things.
Thank you for adding the licenses!

**Comment by kellerkindt** [comment]
Thanks for your feedback. A first implementation can be found on the socket-refactor branch.
