### ISSUE TITLE
Examples of how to construct the Spi and ChipSelect arguments to FourWire would be useful

### ISSUE THREAD

**Issue by mutantbob** [kellerkindt/w5500#31]
I am evaluating using the w5500 crate on an Arduino Uno.  The SPI inteface in `avr_hal_generic` `spi.rs` looks like this:

```Rust
pub fn new(
        p: SPI,
        sclk: port::Pin<port::mode::Output, SCLKPIN>,
        mosi: port::Pin<port::mode::Output, MOSIPIN>,
        miso: port::Pin<port::mode::Input<port::mode::PullUp>, MISOPIN>,
        cs: port::Pin<port::mode::Output, CSPIN>,
        settings: Settings,
    ) -> (Self, ChipSelectPin<CSPIN>) 
```
https://github.com/Rahix/avr-hal/blob/e897783816437a677aa577ddfdaa34e9a1e86d96/avr-hal-generic/src/spi.rs#L147

The fact that it transforms the `Pin<Output,_>` into a `ChipSelectPin<_>` renders it slightly unusable with the `FourWire` .  It is also unclear how I would use this crate at the same time as an OV5642 camera (which also uses the SPI bus), or with the SDcard reader that is physically included in the Arduino Ethernet shield (I think it uses pin 4 for CS).

Then again, the embedded-hal crate appears to be moving toward a new SPI model.

https://github.com/rust-embedded/embedded-hal/pull/351  which is referenced with a quick summary at https://github.com/Rahix/avr-hal/issues/252#issuecomment-1074432318

**Comment by elpiel** [comment]
From what I've read so far, you need to have a locking mechanism for your SPI bus struct in order to be able to share it across multiple peripherals.

**Comment by ryan-summers** [comment]
Check out `shared-bus` (and if you're using RTIC: `shared-bus-rtic`) for examples on how to do this. I would consider SPI bus sharing out-of-scope for this crate.

**Comment by kellerkindt** [comment]
If you can execute all operations at once in the same scope, you can also just borrow the SPI bus and the pin:

```rust
    let mut spi = ...; // SPI interface to use
    let mut cs: OutputPin = ...; // chip select

    let mut device: Option<InactiveDevice<..>> = ...; // maybe: previously initialized device
    let mut socket: Option<Socket> = ...; // maybe: previously opened socket
    
    if let (Some(socket), Some(device)) = (socket.as_mut(), device.as_mut()) {
        let mut buffer = [0u8; 1024];
        match device
            // scoped activation & usage of the SPI bus without move
            .activate_ref(FourWireRef::new(&mut spi, &mut cs))
            .receive(socket, &mut buffer)
        {
            Ok(..) => todo!(),
            Err(..) => todo!(),
        }
    }
```
