### ISSUE TITLE
Releasing w5500

### ISSUE THREAD

**Issue by ryan-summers** [kellerkindt/w5500#35]
I was wondering if it would be possible to cut a new release of 0.4.1 for the `MACRAW` support that got added.

QUARTIQ has been using this functionality for the last year successfully in [booster](https://github.com/quartiq/booster/blob/develop/src/hardware/setup.rs#L329), an embedded RF power amplifier, to allow the W5500 to be used alongside smoltcp to enable things like DHCP without having to add them separately here.

(This is the code I have referred to in previous PRs that is now open-sourced)

I'm looking to get this released so that I can:
1. Release `booster` to crates.io
2. Create a new crate that allows users to easily integrate the `w5500` with `smoltcp`. See https://github.com/quartiq/booster/blob/develop/src/hardware/external_mac.rs for the implementation

**Comment by ryan-summers** [comment]
@kellerkindt Ping on this - any chance we could release it? I'd also be happy to be added as a maintainer on this repo + crates.io if you don't have the bandwidth to maintain the crate :)

**Comment by andresv** [comment]
+1 for @ryan-summers as maintainer.

**Comment by kellerkindt** [comment]
Thanks for the ping, and sorry that I totally forgot about this issue.
[v0.4.1](https://crates.io/crates/w5500) has just been released.
@ryan-summers has been invited for this repo and for crates.io.
