### ISSUE TITLE
Rust may complain when using `embedded-nal` trait objects directly

### ISSUE THREAD

**Issue by ryan-summers** [kellerkindt/w5500#36]
When following the example on the README, there's an issue with the TCP example.

Specifically, the compiler will complain about the `connect()` function being private. This arises because the `TcpSocket` exposes two `connect()` functions - one as a private function, and one as a public trait method of `TcpClientStack`.

[Rust's method call ordering](https://doc.rust-lang.org/reference/expressions/method-call-expr.html) specifies that the private function is found first, which results in the compiler thinking that incorrect arguments and invalid private scope is identified. 

Users can work around this by explicitly casting the socket to a trait object (See https://doc.rust-lang.org/reference/expressions/call-expr.html#disambiguating-function-calls), but this is incredibly not user-friendly.

We should rename all of the private methods of the sockets to not conflict with the trait implementations to avoid this confusion.

**Comment by andresv** [comment]
I was pulling my hair out figuring out what is wrong with the example.

**Comment by andresv** [comment]
Wait a sec this was wrong. It should be like this:

```rust
let mut socket = device.socket().unwrap();
device.connect(&mut socket, SocketAddr::new(IpAddr::V4(Ipv4Addr::new(192, 168, 86, 38)), 8000)).unwrap();
```
