### ISSUE TITLE
WriteTimout when sending data over UDP

### ISSUE THREAD

**Issue by elpiel** [kellerkindt/w5500#41]
I don't know when this setup broke but since 2 days I cannot send any data over UDP and I cannot figure out why.

```rust
pub fn new_device_socket(
    cs_n: ChipSelectPin,
    spi: SPI,
    remote_addr: SocketAddr,
) -> (Device<FourWire<SPI, ChipSelectPin>, Manual>, UdpSocket) {
    let mut device = UninitializedDevice::new(FourWire::new(spi, cs_n))
        .initialize_manual(
            MacAddress::new(18, 1, 2, 3, 4, 5),
            // device:
            Ipv4Addr::new(192, 168, 86, 78),
            Mode {
                on_wake_on_lan: OnWakeOnLan::InvokeInterrupt,
                on_ping_request: OnPingRequest::Respond,
                connection_type: ConnectionType::Ethernet,
                arp_responses: w5500::ArpResponses::Cache,
            },
        )
        .unwrap();

    let mut socket = device.socket().expect("Udp socket");
    device.connect(&mut socket, remote_addr).unwrap();

    (device, socket)
}

...

let remote_addr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(192, 168, 86, 38)), 8000);
let (mut w5500_device, mut udp_socket) = new_device_socket(cs_n, spi, remote_addr);

    loop {
        let data = "Hello world!";
        w5500_device
            .send(&mut udp_socket, data.as_bytes())
            .expect("Should send");
        info!("Sent '{}' over UDP socket: 192.168.86.38:8000", data);
    }
```

I'm using a manual wired connection on Linux:
![Screenshot from 2023-03-10 14-09-59](https://user-images.githubusercontent.com/8925621/224312826-84613a7b-24ab-409b-85be-b17b27da850e.png)

I managed to track the issue to `UdpSocket::send` and that it does not receive any `SendOk` Interrupt and triggers a Timeout eventually:

https://github.com/kellerkindt/w5500/blob/master/src/udp.rs#L65-L76

I bumped into this issue once I wrote my application to use all the available sockets (4 for receiving and 4 for sending) and tried to test it. In that case it didn't even return a Timeout error but hanged the whole microcontroller forever.
I'm using the Pico W5500.

Any ideas what might be causing this?

**Comment by elpiel** [comment]
The only clue I could find is this:

It seems that it send ARP requests and gets a response from my laptop but w5500 returns a Timeout error every single time and no received data is observed in Wireshark.

![Screenshot from 2023-03-12 18-36-42](https://user-images.githubusercontent.com/8925621/224558775-fed59d61-2ffe-4046-8589-3e5f2ac65588.png)


I tried different setups like adding my laptop IP as `192.168.86.1` with default route `192.168.86.1` (as I saw w5500 uses `.1` as the routing address) but the result is still the same - Timeout error when sending.

**Comment by elpiel** [comment]
Today I tested going through a Router and it does work.
Not sure why I managed to make it work before the w5500 and my linux machine without a router for gateway.

I would still like to get some feedback on this.

**Comment by ryan-summers** [comment]
If you're getting ARPs that aren't being responded to, this sounds like a network configuration issue, and not a problem with this crate in my opinion, although I'm not _fully_ following what's going on. In any case, it looks like an ARP is not getting a reply as expected, likely due to network configuration, and there's nothing the W5500 can do during UDP send if it doesn't have the MAC address of the IP you're trying to send to (which is given in the ARP reply).

**Comment by elpiel** [comment]
Ok, thank you! I'm also having issue with sending over UDP but once I figure out what's going on I will open a PR.
