### ISSUE TITLE
Misc Improvments

### ISSUE THREAD

**Issue by jonahbron** [kellerkindt/w5500#8]
This driver is great, thanks very much for making it.  I'm integrating it into my project, and I've been able to get some basic register access working.  There are a number of updates/improvements I'd like to contribute.  Some are benign (like writing more docs about how to set up, etc), while others would be backwards-incompatible (like updating to `embedded_hal::digital::v2`).  Another thing that would be nice is support for 3-wire SPI (no chip-select).

I have lots of ideas how to do these and feel comfortable with taking them on, but I'd like to get a feel for how open you'd be to these kinds of things.  It seems like it would be overall beneficial, especially considering it's still in the 0.x version range.

**Comment by jonahbron** [comment]
@kellerkindt I'll accept your :+1: as a go-ahead. :smile:

**Comment by kellerkindt** [comment]
Thanks jonahbron. I am generally willing to accept PR and happy if anyone likes to contribute to the documentation. I dislike breaking changes, but I accept them when they are reasonable.

So feel free to submit PRs (please tiny ones, one for each concern). Thanks in advance!

(I usually do not respond as fast as this time, so don't worry when you need to wait for an answer for a bit)
